
  timorya-landing-page:
    container_name: timorya-landing-page
    build:
      context: .
      dockerfile: Dockerfile
    image: timorya-landing-page
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always