name: timorya

services:
  timorya-landing-page:
    container_name: timorya-landing-page
    build:
      context: .
      dockerfile: Dockerfile
    image: timorya-landing-page
    environment:
      - PORT=4001
    env_file:
      - .env
    ports:
      - "4001:4001"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always