name: timorya

services:
  timorya-landing-page:
    container_name: timorya-landing-page
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBSITE_API: ${NEXT_PUBLIC_WEBSITE_API}
        NEXT_PUBLIC_WEBSITE_URL: ${NEXT_PUBLIC_WEBSITE_URL}
    image: timorya-landing-page
    environment:
      - PORT=4001
    env_file:
      - .env
    ports:
      - "4001:4001"
    restart: always



